---
title: "chicago_isat"
author: "Amy Tan"
date: "11/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
library(reshape2)
library(janitor)
library(gt)
library(googlesheets4)
library(infer)
library(fs)
library(readxl)
library(rstanarm)
library(reprex)
library(cowplot)
library(stringr)
library(broom)
library(plyr)
library(ggridges)
library(moderndive)
library(data.table)
library(ggthemes)
library(gridExtra)
library(stargazer)
library(ggplot2)
library(grid)
library(tidyverse)
```

```{r}
#x <- read_excel("raw-data/Algebra_exit_exam_2009-2014.xls")

#don't need this for now, so rm
#rm(x)

# doesnt work
#z <- read_excel("raw-data/isat_schools_FINAL_2001_to_2014_yrdown_By_Grade_wELL_Official_20140828")

sheets_deauth()

# reading in ISAT data via google sheets

y <- read_sheet("1aosXO1LMDHl9KMCZvPp4tinTRy3-84FBOfht2xcurBo", skip = 1)

y <- y %>% clean_names() 

```

```{r}

# vector for SE elementary schools

se_elem <- c("BEASLEY", "BEAUBIEN", "BELL", "CARNEGIE", "COONLEY", "EDISON, T", "KELLER", "LENART", "MCPHERSON", "NATIONAL TEACHERS", "PRITZKER", "GREELEY", "OROZCO", "PULASKI", "BRONZEVILLE LTHOUSE CHTR CAMPUS", "DECATUR", "MCDADE", "POE", "SKINNER", "SKINNER NORTH")

# adding markers for SE schools and policy years
## CHANGE THIS TO SCHOOL ID

y <- y %>% 
  mutate(se = ifelse(school_name %in% se_elem, 1, 0)) %>%
  mutate(policy_year = ifelse(year >2010, 1, 0))

# interaction variable between SE schools and policy years

y <- y %>% mutate(did = se * policy_year)


# Estimating the DID estimator:

# using the composite_16 variable since that is the measure of percent of students who exceed ISBE standards

# unlisted the composite_16 variable and created a new variable in order to make it a numeric variable 

y$new_composite_16 <- unlist(y$composite_16)
y$new_composite_16 <- as.numeric(y$new_composite_16)

# also unlisted % exceed for math and reading but didn't create new variables 

y$math_14 <- unlist(y$math_14)
y$math_14 <- as.numeric(y$math_14)
y$read_13 <- unlist(y$read_13)
y$read_13 <- as.numeric(y$read_13)
```


```{r school_demo_data, echo=FALSE}

demo_2006 <- read_xlsx("demo_data/Thesis_demographic_data/2006_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2007 <- read_xlsx("demo_data/Thesis_demographic_data/2007_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2008 <- read_xlsx("demo_data/Thesis_demographic_data/2008_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2009 <- read_xlsx("demo_data/Thesis_demographic_data/2009_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2010 <- read_xlsx("demo_data/Thesis_demographic_data/2010_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2011 <- read_xlsx("demo_data/Thesis_demographic_data/2011_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2012 <- read_xlsx("demo_data/Thesis_demographic_data/2012_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2013 <- read_xlsx("demo_data/Thesis_demographic_data/2013_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2014 <- read_xlsx("demo_data/Thesis_demographic_data/2014_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2015 <- read_xlsx("demo_data/Thesis_demographic_data/2015_schooldemo.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

demo_2006 <- demo_2006 %>% mutate(year = 2006)
demo_2007 <- demo_2007 %>% mutate(year = 2007)
demo_2008 <- demo_2008 %>% mutate(year = 2008)
demo_2009 <- demo_2009 %>% mutate(year = 2009)
demo_2010 <- demo_2010 %>% mutate(year = 2010)
demo_2011 <- demo_2011 %>% mutate(year = 2011)
demo_2012 <- demo_2012 %>% mutate(year = 2012)
demo_2013 <- demo_2013 %>% mutate(year = 2013)
demo_2014 <- demo_2014 %>% mutate(year = 2014)
demo_2015 <- demo_2015 %>% mutate(year = 2015)

```

```{r clean_col_labels, echo=FALSE}
# renamed column names because importing from Excel messed up the column labels

demo_2006 <- setnames(demo_2006, old = c('n','percent', 'n_1', 'percent_1', 'n_2', 'percent_2', 'n_3', 'percent_3', 'n_4', 'percent_4', 'n_5', 'percent_5', 'n_6', 'percent_6', 'n_7', 'percent_7', 'n_8', 'percent_8', 'n_9', 'percent_9', 'n_10', 'percent_10'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_asian', 'percent_asian', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_mexican', 'percent_mexican', 'n_pr', 'percent_pr', 'n_cuban', 'percent_cuban', 'n_otherhisp', 'percent_otherhisp', 'n_multihisp', 'percent_multihisp'))

demo_2007 <- setnames(demo_2007, old = c('n','percent', 'n_1', 'percent_1', 'n_2', 'percent_2', 'n_3', 'percent_3', 'n_4', 'percent_4', 'n_5', 'percent_5', 'n_6', 'percent_6', 'n_7', 'percent_7', 'n_8', 'percent_8', 'n_9', 'percent_9', 'n_10', 'percent_10'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_asian', 'percent_asian', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_mexican', 'percent_mexican', 'n_pr', 'percent_pr', 'n_cuban', 'percent_cuban', 'n_otherhisp', 'percent_otherhisp', 'n_multihisp', 'percent_multihisp'))

demo_2008 <- setnames(demo_2008, old = c('n','percent', 'n_1', 'percent_1', 'n_2', 'percent_2', 'n_3', 'percent_3', 'n_4', 'percent_4', 'n_5', 'percent_5', 'n_6', 'percent_6', 'n_7', 'percent_7', 'n_8', 'percent_8', 'n_9', 'percent_9', 'n_10', 'percent_10'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_asian', 'percent_asian', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_mexican', 'percent_mexican', 'n_pr', 'percent_pr', 'n_cuban', 'percent_cuban', 'n_otherhisp', 'percent_otherhisp', 'n_multihisp', 'percent_multihisp'))

# only five racial categories for 2009 and 2010

demo_2009 <- setnames(demo_2009, old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2', 'no_3', 'pct_3', 'no_4', 'pct_4'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_asian', 'percent_asian', 'n_hisp', 'percent_hisp'))

demo_2010 <- setnames(demo_2010, old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2', 'no_3', 'pct_3', 'no_4', 'pct_4'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_asian', 'percent_asian', 'n_hisp', 'percent_hisp'))

# for 2011-2015, they didn't input much for Asian and separated it into two categories: Asian and Hawaiian/Pacific Islander

# policy change should start to be measured here since it was implemented in its first trial year in 2010-2011, so first calendar year the policy was in effect is demo_2011

demo_2011 <- demo_2011 %>% select(-no_3, -pct_3) %>% setnames(old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2','no_4', 'pct_4', 'no_5', 'pct_5', 'no_6', 'pct_6', 'no_7', 'pct_7', 'no_8', 'pct_8'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_asian', 'percent_asian', 'n_hawpac', 'percent_hawpac', 'n_na', 'percent_na'))

demo_2012 <- demo_2012 %>% select(-no_3, -pct_3) %>% setnames(old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2','no_4', 'pct_4', 'no_5', 'pct_5', 'no_6', 'pct_6', 'no_7', 'pct_7', 'no_8', 'pct_8'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_asian', 'percent_asian', 'n_hawpac', 'percent_hawpac', 'n_na', 'percent_na'))

demo_2013 <- demo_2013 %>% select(-no_3, -pct_3) %>% setnames(old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2','no_4', 'pct_4', 'no_5', 'pct_5', 'no_6', 'pct_6', 'no_7', 'pct_7', 'no_8', 'pct_8'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_asian', 'percent_asian', 'n_hawpac', 'percent_hawpac', 'n_na', 'percent_na'))

demo_2014 <- demo_2014 %>% select(-no_3, -pct_3) %>% setnames(old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2','no_4', 'pct_4', 'no_5', 'pct_5', 'no_6', 'pct_6', 'no_7', 'pct_7', 'no_8', 'pct_8'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_asian', 'percent_asian', 'n_hawpac', 'percent_hawpac', 'n_na', 'percent_na'))

demo_2015 <- demo_2015 %>% select(-no_3, -pct_3) %>% setnames(old = c('no','pct', 'no_1', 'pct_1', 'no_2', 'pct_2','no_4', 'pct_4', 'no_5', 'pct_5', 'no_6', 'pct_6', 'no_7', 'pct_7', 'no_8', 'pct_8'), new = c('n_white','percent_white', 'n_afam', 'percent_afam', 'n_natam', 'percent_natam', 'n_hisp', 'percent_hisp', 'n_multi', 'percent_multi', 'n_asian', 'percent_asian', 'n_hawpac', 'percent_hawpac', 'n_na', 'percent_na'))


test1 <-bind_rows(demo_2006, demo_2007, demo_2008, demo_2009, demo_2010, demo_2011, demo_2012, demo_2013, demo_2014, demo_2015)

# make sure order of commands is in order, in order for these results to be replicated after cleaning the environment

test1 <- test1 %>% clean_names()

for(i in 1:nrow(test1)) {
	if(is.na(test1$school[i])) {
		test1$school[i] <- test1$educational_unit[i]
	}
}

for(i in 1:nrow(test1)) {
	if(is.na(test1$school[i])) {
		test1$school[i] <- test1$education_units[i]
	}
}

# after changing all school names to school name column, there were still 14 NA values/rows that do not correspond to a single school

sum(is.na(test1$school))

test_na <- test1 %>% filter(is.na(school))

# filtering those values out (as well as any missing race values), so only ones with school names present remain

test1 <- test1 %>% filter(!is.na(school)) %>% filter(!is.na(n_white)) %>% filter(!is.na(n_afam)) %>% filter(!is.na(n_natam)) %>% filter(!is.na(n_asian)) %>% filter(!is.na(n_hisp))

```


```{r}
# prob don't need this anymore, old method of filtering for SE schools not using school IDs

se_elem_lower <- c("beasley", "beaubien", "bell", "carnegie", "coonley", "edison", "keller", "lenart", "mcpherson", "national teachers", "pritzker", "greeley", "orozco", "pulaski", "bronzeville", "decatur", "mcdade", "poe", "skinner", "skinner north")


se_schools_demo_list <- test1 %>%
  filter(str_detect(tolower(school), paste(se_elem_lower, collapse = "|"))) %>% pull(school)

# took out the vandepoel from this list because the original vector mistakenly filtered for this via "poe"

se_schools_demo_list_1 <- test1 %>%
  filter(str_detect(tolower(school), paste(se_elem_lower, collapse = "|"))) %>%
  filter(school != "Vanderpoel Magnet") %>%
  filter(school != "John H Vanderpoel Elementary Magnet School") %>%
  filter(school != "VANDERPOEL") %>%
   filter(school != "Noble Street Charter - Pritzker College Prep") %>%
  filter(school != "Bronzeville Scholastic Academy High School") %>%
  filter(school != "Urban Prep Academy for Young Men - Bronzeville") %>%
  filter(school != "Isabelle C O'Keeffe Elementary School") %>%
  filter(school != "LEARN Charter ES - Charles and Dorothy Campbell") %>%
  filter(school != "Bronzeville Mil HS") %>%
  filter(school != "Edison Park Elementary School") %>%
  filter(school != "Edison Park") %>%
  filter(school != "Beasley CPC") %>%
  filter(school != "LEARN CHTR - CAMPBELL") %>%
  pull(school)

x <- test1 %>%
  mutate(policy_year = ifelse(year > 2011, 1, 0)) %>%
  mutate(se_elem = ifelse(school %in% se_schools_demo_list_1, 1, 0)) %>%
  mutate(did = policy_year * se_elem)

```

```{r}

# for appending school IDs to years 2006-2008

se_elem_upper <- c("Beasley Magnet", "Beaubien", "Bell", "Carnegie", "Coonley", "Edison", "Keller Magnet", "Lenart", "Mcpherson", "Natl Teachers Acad", "Pritzker", "Greeley", "Orozco", "Pulaski", "Bronzeville LH Chtr", "Decatur Classical", "McDade Classical", "Poe Classical", "Skinner Classical", "Skinner North")

missing_school_ids <- c("610246", "609796", "609799", "609837", "609866", "609794", "610084", "610298", "610070", "610231", "610229", "609850", "610329", "610138", "400019", "609880", "610066", "610132", "610177", "610534")

# filling in school IDs for missing selective enrollment schools

for(i in 1:nrow(x)) {
	for(j in 1:length(se_elem_upper)) {
		if(x$school[i] == se_elem_upper[j]) {
			x$school_id[i] <- missing_school_ids[j]
		}
	}
}

# filling in missing school IDs - WRONG DONT DO THIS
# for(i in 1:nrow(x)) {
# 	if(is.na(x$school_id[i])) {
# 		x$school_id[i] <- x$unit[i]
# 	}
# }

# so x ONLY has COMPLETE set of school IDs for selective enrollment schools for all years

# labelling each SE school again with school IDs 
x <- x %>% 
  mutate(policy_year = ifelse(year > 2011, 1, 0)) %>% 
  mutate(se_elem = ifelse(school_id %in% missing_school_ids & !is.na(school_id), 1, 0)) %>%
  mutate(did = policy_year * se_elem)

```

```{r}
# Estimating the DID estimator:

# unlisted the n_white variable in order to make it a numeric variable 

x$n_white <- unlist(x$n_white)
x$n_white <- as.numeric(x$n_white)
x$percent_white <- unlist(x$percent_white)
x$percent_white <- as.numeric(x$percent_white)

x$n_afam <- unlist(x$n_afam)
x$n_afam <- as.numeric(x$n_afam)
x$percent_afam <- unlist(x$percent_afam)
x$percent_afam <- as.numeric(x$percent_afam)

x$percent_natam <- unlist(x$percent_natam)
x$percent_natam <- as.numeric(x$percent_natam)
x$n_natam <- as.numeric(x$n_natam)

x$percent_asian <- unlist(x$percent_asian)
x$percent_asian <- as.numeric(x$percent_asian)
x$n_asian <- unlist(x$n_asian)
x$n_asian <- as.numeric(x$n_asian)

x$percent_hisp <- unlist(x$percent_hisp)
x$percent_hisp <- as.numeric(x$percent_hisp)
x$n_hisp <- as.numeric(x$percent_hisp)

x$percent_multi <- unlist(x$percent_multi)
x$percent_multi <- as.numeric(x$percent_multi)
x$n_multi<-as.numeric(x$n_multi)

x$percent_hawpac <- unlist(x$percent_hawpac)
x$percent_hawpac <- as.numeric(x$percent_hawpac)
x$n_hawpac <- unlist(x$n_hawpac)
x$n_hawpac <- as.numeric(x$n_hawpac)

x$total <- as.numeric(x$total)
```

```{r}
# making a new column that combines asian and hawpac for datasets with them
# demographic data from years 2011-2015 have hawpac
# use n_api and percent_api for all subsequent measures that include Asians

# replacing all NA values with a 0 value so that those entries are included
x$percent_asian <- x$percent_asian %>% replace_na(0)
x$percent_hawpac <- x$percent_hawpac %>% replace_na(0)
x$percent_multi <- x$percent_multi %>% replace_na(0)
  
# old code for replacing NA
# x %>% mutate_all(~replace(., is.na(.), 0))

# creating a new variable for API count and percentage
x <- x %>%
  mutate(n_api = n_asian + n_hawpac) %>%
  mutate(percent_api = n_api/total)

```

```{r}
# adding in Herfindahl-Hirschman Index for race column- a measure of overall diversity

x <- x %>% mutate(hhi = ((percent_white/100)^2 + (percent_afam/100)^2 + (percent_api/100)^2 + (percent_hisp/100)^2 + (percent_natam/100)^2 + (percent_multi/100)^2))

# drop district total row (only one without unit and school ID)
x <- x %>% filter(school != "District Total")
```

```{r}
# loaded control variable dataset on three variables

iep_2015 <- read_xlsx("demo_data/chicago_isat_iep_data/iepdata_2015.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

iep_2014 <- read_xlsx("demo_data/chicago_isat_iep_data/iepdata_2014.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

iep_2013 <- read_xlsx("demo_data/chicago_isat_iep_data/iepdata_2013.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

iep_2012 <- read_xlsx("demo_data/chicago_isat_iep_data/iepdata_2012.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

iep_2011 <- read_xlsx("demo_data/chicago_isat_iep_data/iepdata_2011.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

iep_2010 <- read_xlsx("demo_data/chicago_isat_iep_data/iepdata_2010.xlsx", skip = 1, col_names = TRUE, col_types = "text") %>% clean_names()

iep_2015 <- iep_2015 %>% mutate(year = 2015)
iep_2014 <- iep_2014 %>% mutate(year = 2014)
iep_2013 <- iep_2013 %>% mutate(year = 2013)
iep_2012 <- iep_2012 %>% mutate(year = 2012)
iep_2011 <- iep_2011 %>% mutate(year = 2011)
iep_2010 <- iep_2010 %>% mutate(year = 2010)
```

```{r}
# combining iep data vertically

iep_comb <-bind_rows(iep_2015, iep_2014, iep_2013, iep_2012, iep_2011, iep_2010)

# putting all school names into one column

for(i in 1:nrow(iep_comb)) {
	if(is.na(iep_comb$school_name[i])) {
		iep_comb$school_name[i] <- iep_comb$educational_unit_name[i]
	}
}

for(i in 1:nrow(iep_comb)) {
	if(is.na(iep_comb$school_name[i])) {
		iep_comb$school_name[i] <- iep_comb$school[i]
	}
}

# seeing what rows still do not have a school name attached

iep_na <- iep_comb %>% filter(is.na(school_name))

# figured out that these NAs are just district or summary totals, so do not need these rows
# filtering those values out (as well as any missing race values), so only ones with school names present remain

iep_comb <- iep_comb %>% filter(!is.na(school_name))

# decided to keep rows with NA values for any of the 3 variables because they have data for other variables

```

```{r}
# identifying names of schools that do not have a school ID (they are only from 2010-2011)

se_elem_upper_2 <- c("Beasley Magnet", "Beaubien", "Bell", "Carnegie", "Coonley", "Edison", "Keller", "Lenart", "McPherson", "Natl Teachers Acad", "Pritzker", "Greeley", "Orozco", "Pulaski", "Bronzeville LH Chrt", "Decatur Classical", "McDade Classical", "Poe Classical", "Skinner Classical", "Skinner North")


for(i in 1:nrow(iep_comb)) {
	for(j in 1:length(se_elem_upper_2)) {
		if(iep_comb$school_name[i] == se_elem_upper_2[j]) {
			iep_comb$school_id[i] <- missing_school_ids[j]
		}
	}
}

# filling in school_ids with unit and vice versa so every school has at least 1 identifier- WRONGGG DONT DO THIS

# for(i in 1:nrow(iep_comb)) {
# 	if(is.na(iep_comb$school_id[i])) {
# 		iep_comb$school_id[i] <- iep_comb$unit[i]
# 	}
# }
# 
# for(i in 1:nrow(iep_comb)) {
# 	if(is.na(iep_comb$unit[i])) {
# 		iep_comb$unit[i] <- iep_comb$school_id[i]
# 	}
# }

# relabelling se_elem using missing_school_ids vector to make the filtering for selective enrollment more accurate 

iep_comb <- iep_comb %>% 
  mutate(policy_year = ifelse(year > 2011, 1, 0)) %>% 
  mutate(se_elem = ifelse(school_id %in% missing_school_ids & is.na(se_elem), 1, 0)) %>% 
  mutate(did = policy_year * se_elem)

# checked that there were ~120 observations for 20 SE schools with 6 years of data

iep_comb %>% filter(se_elem == 1) %>% nrow()

# relabelling columns to make them more readable

iep_comb <- setnames(iep_comb, old = c('n','percent', 'n_1', 'percent_1', 'n_2', 'percent_2'), new = c('n_bil','percent_bil', 'n_iep', 'percent_iep', 'n_free', 'percent_free'))

# make these into numeric variables

iep_comb$percent_bil <- as.numeric(iep_comb$percent_bil)
iep_comb$percent_iep <- as.numeric(iep_comb$percent_iep)
iep_comb$percent_free <- as.numeric(iep_comb$percent_free)

```


```{r merge}
x_test <- x %>% mutate(new_id = ifelse(!is.na(school_id), school_id, unit))
x_test <- x_test %>% mutate(unique_id = paste0(new_id, year))

iep_comb_2 <- iep_comb %>% filter(school_name != "District Totals")
iep_comb_2 <- iep_comb_2 %>%  mutate(new_id = ifelse(!is.na(school_id), school_id, unit))

# BE CAREFUL
# merging the iep_comb and x datasets to combine info about three student demographics + racial/test score info (respectively) 

master <- merge(x=x_test, y=iep_comb_2, by=c("new_id", "year"), all=TRUE)

# making sure it's the right amount of SE school entries

master %>% filter(school_id.x %in% missing_school_ids) %>% glimpse()

# no ISAT score data for 2015 so filter from other datasets as well for master_2 dataset

master <- master %>% filter(year != 2015)

# merging with ISAT score data 

y <- y %>% filter(year != 2001) %>% filter(year != 2002) %>% filter(year != 2003) %>% filter(year != 2004) %>% filter(year != 2005) 
y_test <- y %>% mutate(new_id = ifelse(!is.na(school_id), school_id, unit))

# merging with all demographic (including IEP) data with score data 

master_2 <- merge(x=master, y=y_test, by=c("new_id", "year"), all=TRUE)

master_2 <- master_2 %>% 
  mutate(policy_year = ifelse(year > 2011, 1, 0)) %>% 
  mutate(se_elem = ifelse(school_id %in% missing_school_ids, 1, 0)) %>% 
  mutate(did = policy_year * se_elem)


```


```{r}
# making bilingualism a control variable (as an example)

# example regression for adding control variable at the school level, after x and iep_comb have been merged

master_2$new_composite_16 <- as.numeric(master_2$new_composite_16)
master_2$se_elem.x <- as.numeric(master_2$se_elem.x)
master_2$se_elem <- as.numeric(master_2$se_elem)

master_2policy_year <- as.numeric(master_2$policy_year)
master_2$did.x <- as.numeric(master_2$did.x)
master_2$did <- as.numeric(master_2$did)
master_2$percent_bil<- as.numeric(master_2$percent_bil)

```




```{r}
# time trends

### slope test for the two lines (written with Robert)
slope_test <- lm(percent_white ~ se_elem*year, data = filter(x, policy_year == 0))

master_2 <- master_2 %>% mutate(year_num = year - 2006)

  
### slope test for the two lines before policy change
slope_test <- lm(percent_white ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))
slope_test1 <- lm(percent_afam ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))
slope_test2 <- lm(percent_natam ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))
slope_test3 <- lm(percent_asian ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))
slope_test4 <- lm(percent_hisp ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))

# should probably put this later since HHI is coded in a later chunk
slope_test5 <- lm(hhi ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))

# slope test for test scores
slope_test6 <- lm(new_composite_16 ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))
slope_test7 <- lm(math_14 ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))
slope_test8 <- lm(read_13 ~ se_elem.x*year_num, data = filter(master_2, policy_year == 0))

# interacting with year gives you the slope difference for a particular group 
slope_test_bil <- lm(percent_bil ~ se_elem*year, data = filter(iep_comb, policy_year == 0))
slope_test_bil2 <- lm(percent_bil ~ se_elem*year + did*year, data = iep_comb)

# do for every slope test to see which was significant
summary(slope_test) 
summary(slope_test1)
summary(slope_test2)
summary(slope_test3)
summary(slope_test4)
summary(slope_test5)
summary(slope_test6)

# slope test 0 had significance for se*year
# slope tests 2 and 4 had significance for year
# sloptest2 had significance for all of them but maybe because Nat. Am. as a group is small?

```

```{r}
# table for slope test results

stargazer(slope_test, slope_test1, slope_test2, slope_test3, 
          slope_test4, slope_test5, slope_test6, slope_test7, slope_test8,
          type="html", 
          dep.var.labels.include = FALSE,
          column.labels = c("% White", "% African American", "% Native American", "% Asian", "% Hispanic", "HHI", "ISAT Composite Scores", "ISAT Math Scores", "ISAT Reading Scores"),
          covariate.labels = c("Selective Enrollment School", "Years", "Selective Enrollment*Years"),
          out="slope_test_all.html")
```


```{r}
# plot parallel slopes for SE and non-SE schools in terms of white demographic

plot2 <- ggplot(x, aes(year, n_white, group = se_elem, color = se_elem)) +
  stat_summary(geom = 'line') +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_minimal()

plot2 <- ggplot(x, aes(year, percent_white, group = factor(se_elem), color = factor(se_elem))) +
  stat_summary(geom = 'line') +
   labs(x= "Year", y = "Percent White") +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
 scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
  theme_bw() 

ggsave("scatter/per_wht.png")
  
# percent Afam by se_elem

plot3 <- ggplot(x, aes(year, percent_afam, group = factor(se_elem), color = factor(se_elem))) +
  stat_summary(geom = 'line') +
   labs(x= "Year", y = "Percent African American") +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
   scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
    theme_bw()

ggsave("scatter/per_afam.png")

# percent Native American

plot4 <- ggplot(x, aes(year, percent_natam, group = factor(se_elem), color = factor(se_elem))) +
  stat_summary(geom = 'line') +
   labs(x= "Year", y = "Percent Native American") +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
   scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
    theme_bw()

ggsave("scatter/per_natam.png")

# percent Asian

plot5 <- ggplot(x, aes(year, percent_asian, group = factor(se_elem), color = factor(se_elem))) +
  stat_summary(geom = 'line') +
   labs(x= "Year", y = "Percent Asian") +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
   scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
    theme_bw()

ggsave("scatter/per_asn.png")

# percent Hispanic

plot6 <- ggplot(x, aes(year, percent_hisp, group = factor(se_elem), color = factor(se_elem))) +
  stat_summary(geom = 'line') +
  labs(x= "Year", y = "Percent Hispanic") +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
   scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
    theme_bw()

ggsave("scatter/per_hsp.png")

```

```{r}
# plot parallel slopes for SE and non-SE schools 
plot6 <- ggplot(x, aes(year, percent_hisp, group = factor(se_elem), color = factor(se_elem))) +
  stat_summary(geom = 'line') +
  labs(x= "Year", y = "Percent Hispanic") +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
   scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
    theme_bw()

ggsave("scatter/per_hsp.png")

#composite scores
score_plot <- ggplot(master_2, aes(year, new_composite_16, group = factor(se), color = factor(se))) +
  stat_summary(geom = 'line') +
   labs(x= "Year", y = "% Exceed ISAT Composite Score Standards") +
  scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_bw() +
  ggsave("score_plot.png")

# math
score_math_plot <- ggplot(y, aes(year, math_14, group = factor(se), color = factor(se))) +
  stat_summary(geom = 'line') +
  labs(x= "Year", y = "% Exceed ISAT Math Score Standards") +
  scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_bw() +
   ggsave("score_math_plot.png")

# reading
score_read_plot <- ggplot(y, aes(year, read_13, group = factor(se), color = factor(se))) +
  stat_summary(geom = 'line') +
  labs(x= "Year", y = "% Exceed ISAT Reading Score Standards") +
  scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_bw() +
   ggsave("score_read_plot.png")

```

```{r}
# DID regression on test scores
# should I add hhi as a variable here?- yes (-robert)

score_reg = lm(new_composite_16 ~ se_elem + policy_year + did, data = master_2)

# + percent_bil-NVM, messes up DID estimate 

score_reg_2 = lm(new_composite_16 ~ se_elem + policy_year + did + hhi, data = master_2)

# score regressions for math
score_reg_math = lm(math_14 ~ se_elem + policy_year + did, data = master_2)

score_reg_math_2 = lm(math_14 ~ se_elem + policy_year + did + hhi, data = master_2)

# score regressions for reading
score_reg_read = lm(read_13 ~ se_elem + policy_year + did, data = master_2)

score_reg_read_2 = lm(read_13 ~ se_elem + policy_year + did + hhi, data = master_2)

# made DID regressions above using master_2 dataset instead to include HHI as a control
# did regression for composite test scores
#didreg = lm(new_composite_16 ~ se + policy_year + did, data = y)
#didreg_math = lm(math_14 ~ se + policy_year + did, data = y)
#didreg_read = lm(read_13 ~ se + policy_year + did, data = y)
```

```{r}
stargazer(score_reg, score_reg_2, 
          score_reg_math, score_reg_math_2, 
          score_reg_read, score_reg_read_2, 
          type="html", 
          dep.var.labels = c("Composite", "Math", "Reading"),
          column.labels = c("Without Control", "With Control", "Without Control","With Control", "Without Control", "With Control"),
          covariate.labels = c("Selective Enrollment School", "Post Policy Change", "Difference-in-difference Estimator", "HHI Score"),
          out="did_by_subject.html")
```


```{r}
# did regression for race
didreg2 = lm(n_white ~ se_elem + policy_year + did, data = x)
didreg2_1 = lm(percent_white ~ se_elem + policy_year + did, data = x)

didreg3 = lm(n_afam ~ se_elem + policy_year + did, data = x)
didreg3_1 = lm(percent_afam ~ se_elem + policy_year + did, data = x)

didreg4 = lm(n_natam ~ se_elem + policy_year + did, data = x)
didreg4_1 = lm(percent_natam ~ se_elem + policy_year + did, data = x)

didreg5 = lm(n_asian ~ se_elem + policy_year + did, data = x)
didreg5_1 = lm(percent_asian ~ se_elem + policy_year + did, data = x)

didreg6 = lm(n_hisp ~ se_elem + policy_year + did, data = x)
didreg6_1 = lm(percent_hisp ~ se_elem + policy_year + did, data = x)

```

```{r}
# DID regression table for race

stargazer(didreg2_1, didreg3_1, didreg4_1, didreg5_1, didreg6_1, 
          type="html", 
          dep.var.labels.include = FALSE,
          column.labels = c("% White", "% African American", "% Native American", "% Asian", "% Hispanic"),
          covariate.labels = c("Selective Enrollment School", "Post Policy Change", "Difference-in-difference Estimator"),
          out="did_by_race.html")
```


```{r}
# regression for bilingualism as a dependent variable 

iep_reg1 = lm(percent_bil ~ se_elem + policy_year + did, data = iep_comb)
summary(iep_reg1)

# regression for special ed as a dependent variable

iep_reg2 = lm(percent_iep ~ se_elem + policy_year + did, data = iep_comb)
summary(iep_reg2)

# regression for free or reduced lunch as a dependent variable

iep_reg3 = lm(percent_free ~ se_elem + policy_year + did, data = iep_comb)
summary(iep_reg3)

# plots of each variable as dependent variables

plot_bil <- ggplot(iep_comb, aes(year, percent_bil, group = se_elem, color = se_elem)) +
  stat_summary(fun.y = mean, geom = 'line') +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_minimal()

plot_iep <- ggplot(iep_comb, aes(year, percent_iep, group = se_elem, color = se_elem)) +
  stat_summary(fun.y = mean, geom = 'line') +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_minimal()

plot_free <- ggplot(iep_comb, aes(year, percent_free, group = se_elem, color = se_elem)) +
  stat_summary(fun.y = mean, geom = 'line') +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_minimal()

```


```{r}
# running DID regression HHI to see how it changed

reg_hhi = lm(hhi ~ se_elem + policy_year + did, data = x)

summary(reg_hhi)

# overall plot of HHI for SE v. non-SE schools

plot_hhi <- ggplot(x, aes(year, hhi, group = factor(se_elem), color = factor(se_elem))) +
  labs(x= "Year", y = "HHI Score") +
  scale_color_manual(name = c("Selective Enrollment \nStatus "), labels = c("Non-SE", "SE"), values = c("blue", "red")) +
  stat_summary(geom = 'line') +
   scale_x_continuous(breaks = 0:2100) +
    geom_vline(xintercept = 2011) +
    theme_bw() +
  ggsave("plot_hhi.png")

```

```{r}
# HHI regression table
stargazer(reg_hhi,
          type="html", 
          dep.var.labels.include = FALSE,
          column.labels = c("HHI Score"),
          covariate.labels = c("Selective Enrollment School", "Post Policy Change", "Difference-in-difference Estimator"),
          out="did_hhi.html")
```


```{r school_level_visualization}

# making a vertical dataset with variables of interest
# master.long <- melt(master, id.vars=c("year", "percent_white", "school_id"))

# creating a ggplot of percent_white change over time for each SE school

# county.graph <- function(df, na.rm = TRUE, ...){
  
  se_school_ids <- c("610246", "609796", "609799", "609837", "609866", "609794", "610084", "610298", "610070", "610231", "610229", "609850", "610329", "610138", "400019", "609880", "610066", "610132", "610177", "610534")

  # plotlist = list()
  # n <- 100
  # 
  # p <- NA
  
for (i in seq_along(se_school_ids)) { # Loop over loop.vector
  
   p <- 
      ggplot(subset(x, x$school_id==se_school_ids[i]),
             aes(year, percent_white, group = school_id)) + 
      geom_line(size=2) +
      facet_wrap( ~  school_id, ncol=5, nrow = 4) +
      geom_vline(xintercept = 2011) +
      theme_pander() +
      theme(legend.position="none") + 
      scale_y_continuous("Percent White") +
      scale_x_continuous("Year", breaks = 0:2100) +
      ggtitle(paste('School: ', se_elem_upper_2[i],'\n', 
                    "Data from Chicago Public Schools \n",
                    sep=''))
      ggsave(p, file=paste0("plot_", i, 
                         # 'projection_graphs/percentwhite_graphs/',
                        #  se_school_ids[i], 
                        ".png", sep=''), scale=2)
     
       plotlist[[i]] = p
   print(p)
}
  
#work on this later
#plot1 <- readPNG('plot1.png')

#test_grid <- grid.arrange(rasterGrob(plot_1),rasterGrob(plot_2),rasterGrob(plot_3), rasterGrob(plot_4), ncol=2)

# can't cowplot them all together because they're .png files, not objects
  
# grid <- plot_grid(plotlist[[1]],plotlist[[2]], labels = c('A', 'B'), label_size = 10)
  # the below didn't work to put the plots into one grid, so try again later
  # p <- grid.arrange(grobs=plotlist, ncol=5, nrow=4)
  # ggsave("bigplot.png", p)
#}

# using function on the master.long dataset

#county.graph(master.long)


# need to figure out how to put plots as objects so it can be used with cowplot

#plot_1 <- system.file("plot_1.png", package = "cowplot")
#plot_2 <- system.file("extdata", "plot_2.png", package = "cowplot")

#plot_grid(plot_1,plot_2, labels = c('A', 'B'), label_size = 10)


```



```{r}
# regression below is for reference ONLY
reg_hhi = lm(hhi ~ se_elem + policy_year + did, data = x)

# making a vertical dataset with variables of interest
hhi.long <- melt(x, id.vars=c("year", "hhi", "school_id"))

# creating a ggplot of percent_white change over time for each SE school

# DON"T USE a for loop WITHIN a function, just keep for loop
# hhi.graph <- function(df, na.rm = TRUE, ...){
  
  se_school_ids <- c("610246", "609796", "609799", "609837", "609866", "609794", "610084", "610298", "610070", "610231", "610229", "609850", "610329", "610138", "400019", "609880", "610066", "610132", "610177", "610534")

# df <- hhi.long 
#  plotlist <- list()

for (i in 1:length(se_school_ids)) { # Loop over loop.vector
  
   hhi_p <- 
      ggplot(subset(df, df$school_id==se_school_ids[i]),
             aes(year, hhi, group = school_id)) + 
      geom_line(size=2) +
      facet_wrap( ~  school_id, ncol=5, nrow = 4) +
      geom_vline(xintercept = 2011) +
      theme_pander() +
      theme(legend.position="none") + 
      
      scale_y_continuous("HHI") +
      scale_x_continuous("Year", breaks = 0:2100) +
      
      ggtitle(paste('School: ', se_elem_upper_2[i],', Chicago, IL \n', 
                    "Data from the Chicago Public Schools website \n",
                    sep=''))
      ggsave(hhi_p, file=paste0("hhiplot_", i, 
                         # 'projection_graphs/percentwhite_graphs/',
                        #  se_school_ids[i], 
                        ".png", sep=''), scale=2)
      
     
       plotlist[[j]] = hhi_p
   
       print(hhi_p)
       
   assign(paste("hhi_p_", i, sep = ""), hhi_p)
   
}
  # the below didn't work to put the plots into one grid, so try again later
  # p <- grid.arrange(grobs=plotlist, ncol=5, nrow=4)
  # ggsave("bigplot.png",p)

}


# using function on the long dataset

x <- hhi.graph(hhi.long)


```

```{r}
# WORKS NOW
# plots of each school's test scores over time

# y$year <- as.numeric(y$year)
# y$year <- unlist(y$year)
# y$new_composite_16 <- as.numeric(y$new_composite_16)
# y$new_composite_16 <- unlist(y$new_composite_16)
# y$school_id <- as.numeric(y$school_id)
# y$school_id <- unlist(y$school_id)
# y$grade <- as.numeric(y$grade)
# y$grade<- unlist(y$grade)
# 
# require(data.table)
# y_edit <- data.table(y)
# 
# y_edit$new_composite_16 <- as.numeric(y_edit$new_composite_16)
# y_edit$new_composite_16 <- unlist(y_edit$new_composite_16)
# 
# # need to input grades
# 
# for(i in 1:5925) {
#   y_edit$grade <- c("3rd grade")
# }
# 
# # example
# hhi.long <- melt(x, id.vars=c("year", "hhi", "school_id"))
# 
# y_edit <- y_edit %>% filter(grade == "3rd grade")

y1 <- y %>% group_by(year, school_id) %>% summarize(mean_score = mean(new_composite_16))

# deframe(y$year)
# deframe(y$new_composite_16)
# deframe(y$school_id)

# making a vertical dataset with variables of interest- DOESN'T WORK- ask why
#test.long <- melt(y, id.vars=c("year", "new_composite_16", "school_id"))

# creating a ggplot of percent_white change over time for each SE school

#test.graph <- function(df, na.rm = TRUE, ...){
  
  se_school_ids <- c("610246", "609796", "609799", "609837", "609866", "609794", "610084", "610298", "610070", "610231", "610229", "609850", "610329", "610138", "400019", "609880", "610066", "610132", "610177", "610534")

  #plotlist = list()
  #n <- 100
  #df2 <- test.long
  
  for (i in seq_along(se_school_ids)) { # Loop over loop.vector
  
   test_p <- 
      ggplot(subset(y1, y1$school_id==se_school_ids[i]),
             aes(year, mean_score, group = school_id)) + 
      geom_line(size=2) +
      geom_vline(xintercept = 2011) +
      theme_pander() +
      theme(legend.position="none") + 
      scale_y_continuous("Test scores") +
      scale_x_continuous("Year", breaks = 0:2100) +
      
      ggtitle(paste('School: ', se_elem_upper_2[i],', Chicago, IL \n', 
                    "Data from the Chicago Public Schools website \n",
                    sep=''))
      ggsave(test_p, file=paste0("testplot_", i, 
                         # 'projection_graphs/percentwhite_graphs/',
                        #  se_school_ids[i], 
                        ".png", sep=''), scale=2)
      
     
       #plotlist[[i]] = p
   print(test_p)
   
     assign(paste("test_p", i, sep = ""), test_p)
}
  
  # the below didn't work to put the plots into one grid, so try again later
  #p <- grid.arrange(grobs=plotlist, ncol=5, nrow=4)
  #ggsave("bigplot.png",p)

#}


# using function on the long dataset

#test.graph(test.long)
```


